apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  namespace: websocket
spec:
  type: NodePort
  selector:
    app: websocket-server
  ports:
    - name: http
      port: 8080        # Service port
      targetPort: 8080  # Container port
      nodePort: 30080   # NodePort for external access
