apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  namespace: websocket
spec:
  type: NodePort
  selector:
    app: websocket-server
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080   # external access
